### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by Becojo** [rubys/nokogumbo#131]
There is a couple of crashes that have been fixed (#129, #128, #126) but a new version has not been released on RubyGems since a year ago. Can you push a new version?

**Comment by stevecheckoway** [comment]
If #132 passes the tests, I'll push out a new gem today.

**Comment by Becojo** [comment]
Awesome thanks!

**Comment by stevecheckoway** [comment]
Done! Version 2.0.2 is now available https://rubygems.org/gems/nokogumbo.
