### ISSUE TITLE
Ruby 2.7.0 warnings

### ISSUE THREAD

**Issue by stevewi** [rubys/nokogumbo#134]
nokogumbo-2.0.2/lib/nokogumbo/html5.rb:74: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

nokogumbo-2.0.2/lib/nokogumbo/html5.rb:21: warning: The called method `parse' is defined here

nokogumbo/html5.rb:22: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

nokogumbo/html5/document.rb:4: warning: The called method `parse' is defined here

**Comment by stevecheckoway** [comment]
Thanks. I haven't tried using 2.7 yet.

As I recall, this was either to match Nokogiri's API or to work around a limitation of older versions of Ruby (or both).

**Comment by stevewi** [comment]
This change is documented in the 2.7 release notes:

https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

**Comment by stevecheckoway** [comment]
Ah, I misunderstood what the issue was. Thanks.

**Comment by MatzFan** [comment]
Is there any chance of another release which incorporates this fix for the Ruby 2.7 warning? Many thanks for the great gem.

**Comment by stevecheckoway** [comment]
Sure, but I'm swamped until the weekend at least.
