### ISSUE TITLE
<source> tag should not be closed

### ISSUE THREAD

**Issue by pierpaolofrasa-twt** [rubys/nokogumbo#14]
The < source >-Tag is an empty element (https://developer.mozilla.org/de/docs/Web/HTML/Element/source).

However, when I do the following:

``` ruby
html = "<source>"
=> "<source>"
irb(main):062:0> Nokogiri::HTML5.parse("<html><body>#{html}").to_html
=> "<html>\n<head></head>\n<body><source></source></body>\n</html>\n"
```

The source tag is closed, which causes all sorts of problems.

I assume this is actually an issue with the underlying c lib, but I wasn't able to check.

**Comment by rubys** [comment]
I would be inclined to accept a pull request with test cases that is similar in size to the lua-gumbo implementation.  Meanwhile, for those who are interested, Wunderbar provides a considerably more heavyweight implementation:
```ruby
> require 'nokogumbo'
> require 'wunderbar'
> html = Nokogiri::HTML5('<source>')
> Wunderbar::XmlMarkup.dump(html)
=> "<!DOCTYPE html>\n<html>\n  <head></head>\n  <body>\n    <source/>\n  </body>\n</html>\n"
```

**Comment by stevecheckoway** [comment]
I suspect that serializing html5 correctly is going to involve implementing the entire serialization spec. I did that [here](https://github.com/stevecheckoway/squoosh/blob/master/lib/squoosh.rb#L266), or at least enough of it for my purposes (which was minifying the source). Maybe some of that could be reused?

**Comment by craigbarnes** [comment]
There's a few tests for [serializing-html-fragments], but they don't really seem comprehensive.

[serializing-html-fragments]: https://github.com/web-platform-tests/wpt/tree/master/html/syntax/serializing-html-fragments

**Comment by stevecheckoway** [comment]
The algorithm for serializing html fragments is surprisingly simple. Mostly because when there are multiple ways to do something, it picks one. For example, when serializing attribute values, it always goes with double quoted strings:
- `foo=bar` becomes `foo="bar"`
- `foo='b"ar'` becomes `foo="b&quot;ar"`
- `foo=bar&baz` becomes `foo="bar&amp;baz"` (in this case the replacement seems a whole lot better)

I was looking at https://github.com/web-platform-tests/wpt/tree/master/encoding for encoding tests of invalid utf8 characters and discovered that gumbo disagrees them but agrees with Firefox (and my reading of the Unicode spec). I guess I should file a bug.

**Comment by stevecheckoway** [comment]
Which is to say that I started implementing the serialization algorithm last night.

**Comment by rubys** [comment]
Cool  Thoughts on what the API would look like?  I would suggest overwriting the `.to_html` method in the object returned by `Nokogiri::HTML5.parse`.

**Comment by stevecheckoway** [comment]
Most of the functions end up calling `write_to`, including `to_html`. I've gotta run right now, but briefly, I introduced `HTML5::Document` and my overridden `write_to` does this check (not tested yet)

``` ruby
        if (config_options & (SaveOptions::AS_XML | SaveOptions::As_XHTML) != 0)
           || !document.is_a?(HTML5::Document)
          # Use Nokogiri's serializing code.
          native_write_to(io, encoding, indent_string, config_options)
        else
          # Serialize including the current node.
          HTML5.serialize_node_to(self, io, encoding, indent_string, config_options)
        end
```

**Comment by stevecheckoway** [comment]
@pierpaolofrasa-twt I realize this is now many years later, but a fix for this should be in the next version.

``` ruby
> Nokogiri::HTML5('<source>').to_html
=> "<html><head></head><body><source></body></html>"
```
