### ISSUE TITLE
please tag 2.0.2 

### ISSUE THREAD

**Issue by boutil** [rubys/nokogumbo#142]
Hi,

I noticed that rubygems has a 2.0.2 version of nokogumbo, whereas there is no tag on the git repository corresponding to this version. In Debian, we would like to use the git repository as the source of your gem to include tests in our packaging process.

Would you mind adding a tag for the 2.0.2 version?

Thanks a lot.

Cédric

**Comment by stevecheckoway** [comment]
I just did. Thanks for catching that!

**Comment by boutil** [comment]
thanks!
