### ISSUE TITLE
Fix O(n^2) behavior when checking for duplicate attributes

### ISSUE THREAD

**Issue by stevecheckoway** [rubys/nokogumbo#144]
Code in question is [here](https://github.com/rubys/nokogumbo/blob/master/gumbo-parser/src/tokenizer.c#L792).

This can lead to a DoS. See #143.

**Comment by flavorjones** [comment]
@stevecheckoway Do we still need to address this? If so, should we move this issue over to Nokogiri?

**Comment by stevecheckoway** [comment]
I think so.

My recollection is that libxml2 checks for duplicate attributes whenever an attribute is added to an element and the only way it has to do this is by walking the linked list of attributes.

If we want to manipulate the `xmlNode` structure directly rather than calling functions to modify it, we should be able to get amortized O(n) behavior by collecting the set of attributes to add and checking for duplicates.

**Comment by flavorjones** [comment]
Moved to https://github.com/sparklemotion/nokogiri/issues/2568
