### ISSUE TITLE
GitHub Actions tests too often

### ISSUE THREAD

**Issue by stevecheckoway** [rubys/nokogumbo#168]
The current GitHub Actions setup (which was mostly copied from somewhere else) builds and tests twice when pull requests are created. I think the behavior we want is to build/test once for each
- push to `master`;
- creation of a pull request; and
- push to a pull request branch other than the first.

After skimming [this](https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662), it's not obvious to me if it's possible or not possible.

**Comment by flavorjones** [comment]
I think I've fixed this with the most recent commit on #167

**Comment by stevecheckoway** [comment]
Will that still build on a push to a pull request branch? In other words, when a PR is opened, it will build. But if a change is made to the PR and then pushed, will that build again?

**Comment by flavorjones** [comment]
:thinking: Let me test that.

**Comment by flavorjones** [comment]
@stevecheckoway You were right, they weren't being re-triggered. BRB, going to fix Nokogiri's Actions config.

**Comment by stevecheckoway** [comment]
That's too bad. There's probably a way to work around it, but it seems like something GitHub needs to fix.

**Comment by flavorjones** [comment]
@stevecheckoway Ah, found a thing that works, see https://github.com/rubys/nokogumbo/pull/167/commits/a7ca22b757f61f3e0d8e274864665e4c09343029
