### ISSUE TITLE
HTML5 Validation?

### ISSUE THREAD

**Issue by shaqq** [rubys/nokogumbo#19]
@rubys 

Do you know if this gem allows HTML5 validation of any sort? I seem to get this to work properly:

``` ruby
Nokogiri::HTML5('<html text </html').errors
# => []
```

**Comment by rubys** [comment]
Not possible until gumbo-parser adds the underlying functionality.  This is being tracked with the following issue:

https://github.com/google/gumbo-parser/issues/39

**Comment by stevecheckoway** [comment]
Just now seeing this. #46 should do what you want. It uses Gumbo's internal error mechanism. If that patch (or a similar one) is accepted, someone should tell the Gumbo people how the error API is being used here. I imagine that, eventually, they'll move to a public API.

**Comment by stevecheckoway** [comment]
@shaqq I believe this is now supported by nokogumbo. You just need to specify how many errors you want to receive.

``` ruby
Nokogiri::HTML5('<html text </html', max_parse_errors: 10).errors
```

```
irb(main):007:0> Nokogiri::HTML5('<!DOCTYPE html><html text </html', max_parse_errors: 10).errors.each do |err| puts err.to_s end
1:27: ERROR: @1:27: Tokenizer error with an unimplemented error message.
<!DOCTYPE html><html text </html
                          ^
1:29: ERROR: @1:29: Tokenizer error with an unimplemented error message.
<!DOCTYPE html><html text </html
                            ^
1:33: ERROR: @1:33: Tokenizer error with an unimplemented error message.
<!DOCTYPE html><html text </html
                                ^
```

The error messages for these particular errors aren't great. I'm going to close this now.

**Comment by shaqq** [comment]
@stevecheckoway cool, thanks!
