### ISSUE TITLE
Flooding of warning saying: "element span: validity error : ID login_btn already defined"

### ISSUE THREAD

**Issue by Basher52** [rubys/nokogumbo#21]
Hi

I'm using nokogumbo as a parser and I'm getting flooded with warnings/messages saying:
element span: validity error : ID login_btn already defined

I boiled down my code and was able to reproduce it with the following code:
require 'open-uri'
require 'nokogumbo'
file = open('http://www.motogp.com/en/Results+Statistics')
doc = Nokogiri::HTML5(file)

The error comes out 2x after performing the 'doc = Nokogiri::HTML5(file)' command.

Would it be possible to supress this message/warning?
Thanks for the help!
Cheers

**Comment by rubys** [comment]
This message is not put out by nokogiri.  It seems to be a problem in libxml2.

Issue https://github.com/sparklemotion/nokogiri/issues/1208 was closed with a message that https://github.com/sparklemotion/nokogiri/issues/1196 was re-opened.  Issue https://github.com/sparklemotion/nokogiri/issues/1196 was closed saying open a new issue.

**Comment by rubys** [comment]
On further investigation, it appears that libxml2 changed, and nokogiri had to change to capture these messages, and that a similar fix is necessary to nokogumbo.

**Comment by Basher52** [comment]
I'm still new to github, but i think i understand that your commit should now supress these messages.
So by updating my nokogumbo I assume it should be fixed.
Thanks a lot for the effort and help!

**Comment by rubys** [comment]
hold back for the moment, this fix is broken, I'm still chasing down what the real fix should be.

**Comment by Basher52** [comment]
Roger that, I'm not home at the moment but thanks for the heads up

**Comment by flavorjones** [comment]
@rubys Let me know if I can assist in any way, having been through a few iterations of this fix on Nokogiri already. ;)

**Comment by rubys** [comment]
Reproducible test case for the problem, with no Nokogumbo:

    require 'nokogiri'
    doc = Nokogiri::HTML::Document.new()
    x1 = Nokogiri::XML::Element.new('a', doc)
    x1.set_attribute('id', 'x')
    x2 = Nokogiri::XML::Element.new('a', doc)
    x2.set_attribute('id', 'x')

**Comment by rubys** [comment]
Opened as https://github.com/sparklemotion/nokogiri/issues/1262

**Comment by rubys** [comment]
Fixed: https://github.com/sparklemotion/nokogiri/commit/f49e439146b951e35d169110fefe4d5882399d62

**Comment by rafbm** [comment]
Isn’t this back? I’m having such warnings when using Nokogumbo only, not with plain Nokogiri.

```ruby
require 'nokogumbo'
Nokogiri::HTML5('<p id="foo"></p><p id="foo"></p>')
# => element p: validity error : ID foo already defined
```
```ruby
require 'nokogiri'
Nokogiri::HTML('<p id="foo"></p><p id="foo"></p>')
# => nothing
```

Nokogiri: 1.6.7.2
Nokogumbo: 1.4.7
