### ISSUE TITLE
wraps closed div tags around everything

### ISSUE THREAD

**Issue by grosser** [rubys/nokogumbo#29]
this seems pretty broken :(

```
Nokogiri::HTML5.parse('<div />aaa').to_s
"<?xml version=\"1.0\"?>\n<html>\n  <head/>\n  <body>\n    <div>aaa</div>\n  </body>\n</html>\n"
```

... nokogiri does  it just fine:

```
Nokogiri::HTML.parse('<div />aaa').to_s
"<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\n<html><body>\n<div></div>aaa</body></html>\n"
```

@rubys any ideas how I can fix this ?

**Comment by rubys** [comment]
The question you should be asking yourself is: do you want to parse input as browsers do (i.e., not recognizing self closing tag syntax, and fixing things up by closing all open tags at the end), or as XML does (i.e., recognizing self closing tag syntax).  If the former: use nokogumbo.  If the latter, use nokogiri.

**Comment by grosser** [comment]
... ahhh ... 

so the problem then is 
correct html -> nokogiri -> correct xml -> nokogiri -> incorrect html :D


```
Nokogiri::HTML5.parse('<div></div>aaa').to_s
=> "<?xml version=\"1.0\"?>\n<html>\n  <head/>\n  <body><div/>aaa</body>\n</html>\n"
```

now has self-closing tags ...

```
Nokogiri::HTML5.parse(Nokogiri::HTML5.parse('<div></div>aaa').to_s).to_s
=> "<?xml version=\"1.0\"?>\n<html>\n  <head>\n  </head>\n  <body>\n    <div>aaa\n\n</div>\n  </body>\n</html>\n"
```

**Comment by grosser** [comment]
ok, got it `.to_xhtml` :D 

Want that in the readme ?

**Comment by grosser** [comment]
```
Nokogiri::HTML5.parse(Nokogiri::HTML5.parse('<div></div>aaa').to_xhtml).to_xhtml
=> "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns=\"http://www.w3.org/1999/xhtml\"><head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n</head>\n  <body><div></div>aaa\n\n</body></html>\n"
```

**Comment by rubys** [comment]
> Want that in the readme ? 

Pull requests with updates to the README would be most welcome!

**Comment by grosser** [comment]
https://github.com/rubys/nokogumbo/pull/30
