### ISSUE TITLE
Support Nokogiri::HTML.parse method signature

### ISSUE THREAD

**Issue by gkellogg** [rubys/nokogumbo#31]
`Nokogiri::HTML5.parse` accepts a single argument, a String. However `Nokogiri::HTML.parse` accepts three, the string or readable, a base uri, and encoding. I'd be happy if the encoding argument were ignored, but to be a plug-replacement for Nokgori::HTML, it should accept a base URI for turning relative URLs into absolute URLs.

**Comment by rubys** [comment]
The [documentation for nokogiri](http://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/HTML/Document) isn't particularly clear.  The most I can find is:

> url is resource where this document is located

I also can't figure out a way to set a URL *without* calling parse.  Perhaps if a url is provided, I can call HTML parse, throw away the document that is created, and replace it?

In any case, it would be helpful to know what behavior you are expecting if a url is provided.  Would this change the values of `href` attributes of `<a>` elements, for example?

**Comment by gkellogg** [comment]
The behavior I expect, and utilize with Nokogiri is for resolving relative URLs contained within the HTML document. I use this as I want to be able to turn such URLs in to absolute URLs, but you're right that it's unclear exactly what Nokogiri does with this. In may case, I need to resolve relative URLs for generating RDF, which requires absolute URIs, but it may be that passing this to Nokogiri isn't useful.

It certainly doesn't seem that Nokogiri throws away the input and uses the `url` argument instead.

However, it is part of the method signature (as is encoding), so it seems reasonable to allow for such arguments, even if they are actually ignored by Nokogumbo, as this truly allows `Nokogiri::HTML5.parse` to be a plug replacement for `Nokogiri::HTML.parse` from an API perspective.

In my case, I really need validation support as well, which is in #19. I can certainly work around this particular issue, so it's more a "nice to have".

Note that `Nokogiri::HTML.parse(%(<a href="foo">foo</a>), "http://example.org/doc").to_html` does not seem to cause the href to become absolute.

Presumably, Nokogiri ends up calling something like [htmlCtxtReadDoc](http://www.xmlsoft.org/html/libxml-HTMLparser.html#htmlCtxtReadDoc), so Nokogiri adds it for use by LibXML2 for whatever use.

**Comment by stevecheckoway** [comment]
The URL parameter gets passed to `htmlReadIO` which passes it to `htmlDoRead` which stores a copy in a `filename` parameter of a context structure that gets passed around while parsing. As near as I can tell, `filename` is used only for XML entities and error messages.

Nokogiri also supports a block on `parse` for setting options. None of the url, encoding, or block parameters seem particularly useful for `HTML5.parse`.

Can you give an example of how you're using Nokogiri to resolve relative URLs?

**Comment by gkellogg** [comment]
Given an href, or similar, the associated URL, if not absolute, is resolved relative to the document location, or base as defined in the head. If loaded locally, there is no base, so setting one through an option or argument is common for parsers.

Without this, the DOM will contain relative URLs, for the application to resolve. Not the end of the world, but seemingly inconsistent with other parsers. When writing a gem that might use different parsers, consistency is useful.

**Comment by stevecheckoway** [comment]
I mean, can you give an example where using `Nokogiri::HTML.parse` does this relative to absolute transformation but `Nokogiri::HTML5.parse` does not. When I was looking through libxml2 yesterday, I didn't see anything that looked like that behavior, but it's a large library so it's certainly possible I missed something.

**Comment by gkellogg** [comment]
So, it looks like this is not a problem at all; I removed passing the URL from my Nokogiri implementation, and it didn't change the outcome from any specs. Relative URI resolution must be handled elsewhere.

I'll take another stab ad doing an Nokogumbo adaptor and see if I can just close out this issue. It's been some time since I last looked at it.

**Comment by gkellogg** [comment]
Since I last had tried this, the intervening updates seem to have addressed all issues I had, and it is a clean replacement for Nokogiri::HTML.parse. Thanks for the great gem!
