### ISSUE TITLE
Template Tag Support

### ISSUE THREAD

**Issue by jbotelho2-bb** [rubys/nokogumbo#32]
I noticed that you added and then commented out template support in 5bcd5a6. This is problem when processing documents containing this tag, because the entire tag and all its children are thrown out of the document. Uncommenting the code seems to work fine.

Was there a specific reason you removed this?

**Comment by rubys** [comment]
IIRC, at the time it depended on an unreleased version of the gumbo parser.  It likely is OK to add back in now.

**Comment by rubys** [comment]
FIxed in https://github.com/rubys/nokogumbo/commit/70e233b612a747af5d4c0c839272fcebf7938c18
Released in https://rubygems.org/gems/nokogumbo/versions/1.4.4
