### ISSUE TITLE
special characters are escaped in CDATA segments

### ISSUE THREAD

**Issue by dan42** [rubys/nokogumbo#33]
Examples speak louder than words:

    >> puts Nokogiri::HTML5.fragment('<script> if (a < b) alert(1) </script>')
    <script> if (a &lt; b) alert(1) </script>

    >> puts Nokogiri::HTML5.fragment('<style> .a > .b { color:red; } </style>')
    <style> .a &gt; .b { color:red; } </style>

So if we try to parse html, modify a few elements, and output the result, `script` and `style` tags will not survive the trip. (Neither will `xmp` and `plaintext` tags, but obviously that's less of a problem.) This escaping doesn't occur with Nokogiri::HTML.fragment.

**Comment by rubys** [comment]
And yet, 

    > puts Nokogiri::HTML.fragment('<script> if (a < b) alert(1) </script>').children[0].text
     if (a < b) alert(1)

    > puts Nokogiri::HTML5.fragment('<script> if (a < b) alert(1) </script>').children[0].text
     if (a < b) alert(1)

So the question is: what is different between the two objects?  I've looked at `.class`, '.xml?`, `.html?` and can find no difference.  If you can help me find an observable difference, I can backtrack to see what changes to the code are necessary to make that difference go away.

**Comment by dan42** [comment]
Hmmm... well here's *one* difference
```
>> str = '<script> if (a < b) alert(1) </script>'
>> Nokogiri::HTML5.fragment(str).children[0].children
=> [#<Nokogiri::XML::Text:0x3fa45ea00004 " if (a < b) alert(1) ">]

>> Nokogiri::HTML.fragment(str).children[0].children
=> [#<Nokogiri::XML::CDATA:0x3fa45ea0412c " if (a < b) alert(1) ">]
```

**Comment by dan42** [comment]
Ok, I've looked at this some more and while it's a bit hard to wrap my head around the gumbo lexer+parser, it seems that:

1. The only way to have a Nokogiri::XML::CDATA node is if `(GumboNode* child)->type == GUMBO_NODE_CDATA` (nokogumbo.c:167)
2. The only place where the GUMBO_NODE_CDATA constant is assigned to anything is when `token->type == GUMBO_TOKEN_CDATA` (parser.c:1125)
3. The only place where token->type is assigned that value is when `parser->_tokenizer_state->_is_in_cdata` is true (tokenizer.c:483)
4. The only way for _is_in_cdata to be true is if the tokenizer encounters a `<![CDATA[` declaration in a "foreign" node like SVG (tokenizer.c:2003)

Testing this theory:

    >>  Nokogiri::HTML5.fragment('<svg><![CDATA[ foo ]]>').children[0].children
    => [#<Nokogiri::XML::CDATA:0x3fa45ea1e1bc "<![CDATA[ foo ]]>">]

So.

It seems that for gumbo, a "cdata" node means an actual <![CDATA[ declaration, while for Nokogiri it means a node with raw text ("&amp;eacute;" maps to "&amp;eacute;", not "é")

I think that in nokogumbo.c:164 we need something like

      case GUMBO_NODE_TEXT:
        if tag name is script|style|xmp|plaintext
          node = xmlNewCDataBlock(document, 
            CONST_CAST child->v.text.original_text.data,
            (int) child->v.text.original_text.length);
        else
          node = xmlNewDocText(document, CONST_CAST child->v.text.text);
        break;

**Comment by rubys** [comment]
Complete set, from [Parsing HTML fragments](https://html.spec.whatwg.org/multipage/syntax.html#parsing-html-fragments):

* RCDATA
   * `title`
   * `textarea`

* RAWTEXT
   * `style`
   * `xmp`
   * `iframe`
   * `noembed`
   * `noframes`

* PLAINTEXT
   * `plaintext`


`noscript` needs further investigation.

**Comment by dan42** [comment]
parser.c:4037:

      case GUMBO_TAG_NOSCRIPT:
        /* scripting is disabled in Gumbo, so leave the tokenizer
         * in the default data state */
        break;

So the content inside a `<noscript>` tag is parsed like regular html. And the noscript tag itself is treated like a void element:

    >>  Nokogiri::HTML5.fragment('<noscript><div></div></noscript>').children
    => [#<Nokogiri::XML::Element:0x3fa45e9ebc58 name="noscript">, #<Nokogiri::XML::Element:0x3fa45e9ebb90 name="div">]

**Comment by dan42** [comment]
Hmmm, another slighty related problem:

    >> Nokogiri::HTML.fragment("<div>").to_s
    => "<div></div>"
    >> Nokogiri::HTML5.fragment("<div>").to_s
    => "<div/>"

**Comment by rubys** [comment]
Hmm.  The effect of using `xmlNewCDataBlock`:

    <script><![CDATA[ if (a < b) alert(1) ]]></script>

There must be another difference involved.

**Comment by dan42** [comment]
I think I have it.

    >> Nokogiri::HTML.fragment("<script>").document.html?
    => true
    
    >> Nokogiri::HTML5.fragment("<script>").document.html?
    => false

The parent document is not marked as html, so the nodes are rendered with to_xml instead of to_html. The text node needs to be CDATA in order to avoid escaping special characters, and the document needs to be html in order to avoid the <![CDATA[ declaration.

**Comment by rubys** [comment]
So the next question is: how do I initially create (or subsequently mark) a document fragment as HTML?

Here's what the current code is doing:

    >> doc = Nokogiri::HTML::Document.new()
    => #<Nokogiri::HTML::Document:0x16814a0 name="document" children=[#<Nokogiri::XML::DTD:0x168116c name="html">]>

    >> frag = Nokogiri::HTML::DocumentFragment.new(doc)
    => #<Nokogiri::HTML::DocumentFragment:0x1685988 name="#document-fragment"> 

    >> frag.html?
    => false

**Comment by rubys** [comment]
Progress:

    xmlDocPtr doc = xmlNewDoc(CONST_CAST "1.0");
    doc->type = XML_HTML_DOCUMENT_NODE;

**Comment by dan42** [comment]
Haha! yeah, that's one way of doing it.

    d=Nokogiri::XML::Document.new
    d.class #=> Nokogiri::XML::Document
    d.type  #=> 9

    d=Nokogiri::HTML::Document.new
    d.class #=> Nokogiri::HTML::Document
    d.type  #=> 13

    d=Nokogiri.HTML5("<div>").document
    d.class #=> Nokogiri::HTML::Document
    d.type  #=> 9

The document has the right class but the wrong type. I'm completely mystified as to where doc->type is usually initialized. Inside libxml?

**Comment by rubys** [comment]
I'll push out a new gem in a day or so.

**Comment by dan42** [comment]
Thanks! Although technically, `script` and `style` tags should be CDATA nodes in order to match the behavior of `Nokogiri.HTML()`, strangely it seems to have no effect on output.
