### ISSUE TITLE
Gem fails to build on systems without libxml2

### ISSUE THREAD

**Issue by jbotelho2-bb** [rubys/nokogumbo#34]
In f7d3d66b0b9275ecf1c7b584d41365fc1a1a5e82, a reference was added to `XML_HTML_DOCUMENT_NODE`, which seems to be defined by libxml2. This causes the compilation to fail when libxml2 is not available on the system at compile-time, which contradicts the note in the Readme about being able to compile without libxml2 headers.

To was easily to reproduce on travis by uninstalling libxml2 before building: https://travis-ci.org/jbotelho2-bb/nokogumbo/jobs/88422106

**Comment by rubys** [comment]
Good catch!  Can you give the above fix a try?  If it solves the problem, I'll push out a new gem.

**Comment by jbotelho2-bb** [comment]
Seems to still break without libxml. I'm not too familiar with ruby C extension, so I'm not entirely sure how to fix it. It seems like its expecting `doc->type` to be assigned differently than a normal struct.

**Comment by rubys** [comment]
Can you share the error message you are seeing?

**Comment by rubys** [comment]
Reproduced:

    nokogumbo.c:196:6: error: invalid type argument of ‘->’ (have ‘VALUE’)
       doc->type = XML_HTML_DOCUMENT_NODE;
          ^

Now, I'm back to the original problem... I see no way using the Nokogiri Ruby interface to set this.  :-(

**Comment by rubys** [comment]
I'm getting a compile time warning that I don't fully understand (passing a NULL as a first argument), but it doesn't seem to cause any problem at runtime, and the tests all pass.    Let me know if you see any problem, and I'll reopen.  Or let me know that this works for you, and I'll push out a new gem.

**Comment by jbotelho2-bb** [comment]
Looks like its working now. Thanks for the quick fix.
