### ISSUE TITLE
Fork gumbo-parser?

### ISSUE THREAD

**Issue by stevecheckoway** [rubys/nokogumbo#52]
Google's gumbo-parser has a few bugs and it's not clear that it's actually maintained any longer. I worked around https://github.com/google/gumbo-parser/pull/371 in https://github.com/rubys/nokogumbo/pull/51 but https://github.com/google/gumbo-parser/pull/375 seems potentially bad.

Two options spring to mind:

1. Incorporate an updated version of gumbo-parser directly in nokogumbo.
2. Fork gumbo-parser and point the git submodule at the fork.

In either case, fixes could be applied. I suspect 2 would be easier to do and easier to revert if gumbo starts being updated again.

**Comment by rubys** [comment]
I would accept a pull request for either.  Looks like google/gumbo-parser#375 has a pull request waiting on a CLA being signed.  (Additionally, it looks like there is a test failing, but I haven't looked into whether that was pre-existing or as a result of the change).

**Comment by stevecheckoway** [comment]
The failing test isn't related. The `.travis.yml` file contains the wrong url for gtest. I submitted a PR about that on the off chance it's actually being maintained.

**Comment by stevecheckoway** [comment]
Related bug https://github.com/rubys/nokogumbo/issues/64.

**Comment by stevecheckoway** [comment]
Addressed by https://github.com/rubys/nokogumbo/commit/4217876d0ca293b91c6f3feddf1d1418942c8548.
