### ISSUE TITLE
Nokogumbo 1.4.12 crashes on Heroku

### ISSUE THREAD

**Issue by brchristian** [rubys/nokogumbo#61]
Deploying Nokogumbo 1.4.12 to Heroku, my apps crash and will not load:

```ruby
LoadError: /tmp/build_cb6d9f00a9684138f8fafb6ab936331c/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.7.2/ext/nokogiri/nokogiri.so: cannot open shared object file: No such file or directory - /tmp/build_a52ff056ecc70c6737ee489b9e26c490/vendor/bundle/ruby/2.4.0/gems/nokogumbo-1.4.12/lib/nokogumboc.so
```

**Comment by matthewrudy** [comment]
I get the same,
rolled back to 1.4.11

**Comment by zunda** [comment]
Same here on Heroku. It seems that location of `nokogiri.so` when `nokogumboc.so` was built persists while they are built under a temporary directory on Heroku.

**Comment by rubys** [comment]
Let me know if 1.4.13 fixes the problem

**Comment by benedikt** [comment]
@rubys 1.4.13 fixed this for me. Thanks!

**Comment by zunda** [comment]
Same here again. 1.4.13 worked! Thank you!

**Comment by brchristian** [comment]
Looks good on our side too. Closing this issue!

**Comment by robbat2** [comment]
@brchristian On the Heroku environment, where does the final `nokogiri.so` end up living? The rpath passed during building needs to reflect that.

Reverting the commit has broken it on Gentoo again :-(.

**Comment by brchristian** [comment]
@robbat2 To be honest I am not sure; maybe someone who is more familiar with the Heroku deploy process can chime in here...

**Comment by zunda** [comment]
Heroku runs `bundle install` under a random [`BUILD_DIR`](https://devcenter.heroku.com/articles/buildpack-api#bin-compile) like `/tmp/build_cb6d9f00a9684138f8fafb6ab936331c/`. When the app is running, artifacts are extracted under `/app`.

**Comment by robbat2** [comment]
@zunda can you help me debug this on Heroku then? Right where the LoadError happens, I'd like to the output of `find $BUILD_DIR -path '*nokogiri*' Trying to understand why it has two different $BUILD_DIR values in the output.

**Comment by zunda** [comment]
Sorry to be unclear here. `$BUILD_DIR` is only available when the app is being built. Resulting files are packed into a tar file and extracted onto a different environment under a different path, namely `/app`, when the app is being executed. Here is what I see for a minimal Heroku app with nokogumbo 1.4.12:

```
$ heroku run bash
Running bash on ⬢ nokogumbo-builddir... up, run.6226 (Free)
~ $ grep nokogumbo Gemfile
gem 'nokogumbo', '1.4.12'
~ $ ruby -r nokogumbo -e ''
/app/vendor/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': /tmp/build_b4c26808c0ddf9588bebace1bf64dc0f/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/ext/nokogiri/nokogiri.so: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.4.0/gems/nokogumbo-1.4.12/lib/nokogumboc.so (LoadError)
  from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from /app/vendor/bundle/ruby/2.4.0/gems/nokogumbo-1.4.12/lib/nokogumbo.rb:2:in `<top (required)>'
  from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
  from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
  from /app/vendor/ruby-2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
~ $ ldd /app/vendor/bundle/ruby/2.4.0/gems/nokogumbo-1.4.12/lib/nokogumboc.so | grep nokogiri
  /tmp/build_b4c26808c0ddf9588bebace1bf64dc0f/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/ext/nokogiri/nokogiri.so => not found
~ $ find / -name nokogiri.so 2>/dev/null
/app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/ext/nokogiri/nokogiri.so
/app/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/lib/nokogiri/nokogiri.so
/app/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/nokogiri-1.8.1/nokogiri/nokogiri.so
~ $ ls /tmp/build_b4c26808c0ddf9588bebace1bf64dc0f
ls: cannot access '/tmp/build_b4c26808c0ddf9588bebace1bf64dc0f': No such file or directory
```

I hope this helps. Just let me know anything else that may help.

**Comment by robbat2** [comment]
Ok, from the above, during build time, nokogumbo is finding nokogiri in that `$BUILD_DIR`, and not in `/app/`.
Does the Gemfile explicitly involve nokogiri before nokogumbo?
eg:
```
gem 'nokogiri'
gem 'nokogumbo'
```
or does it only contain `nokogumbo`?

Either way, the rpath during building (which gets included in the ELF) needs to reference the `/app` path to nokogiri.
