### ISSUE TITLE
Please add a git tag for releases

### ISSUE THREAD

**Issue by gfx** [rubys/nokogumbo#63]
To check differences between versions easily.

Thanks.

**Comment by suweller** [comment]
This would greatly simplify my workflow with regards to using `nokogumbo` as well. Here's [an example](https://github.com/suweller/mongoid-autoinc/blob/master/Rakefile) of how I do it.

Please consider adding release tags.

**Comment by stevecheckoway** [comment]
Done for 2.0.0.
