### ISSUE TITLE
Crash with unicode NULL

### ISSUE THREAD

**Issue by mesge** [rubys/nokogumbo#64]
Nokogumbo can have a nasty crash when parsing html tags that contain unicode null characters.

**Steps to reproduce:**

```ruby
require 'nokogiri'
require 'nokogumbo'

str = "<\u0000/\u0000>" # </>
Nokogiri::HTML5.parse str
```
```
Assertion failed: (*c || c == error_location), function find_last_newline, file error.c, line 141.
[1]    64965 abort      irb
```

**See also these strings:**
```
<\u0000/\u0000h\u0000t\u0000m\u0000l\u0000>
```
```
<html><body><\u0000/\u0000b\u0000o\u0000d\u0000y\u0000><\u0000/\u0000h\u0000t\u0000m\u0000l\u0000>
```

Version tested: `1.8.1`
Ruby version: `2.3.4`

**Comment by stevecheckoway** [comment]
This looks like a bug in the gumbo parser. This [comment](https://github.com/google/gumbo-parser/blob/master/src/error.c#L140) suggests the authors didn't consider embedded 0 bytes. This bug provides more evidence that we should probably fork gumbo and fix the bugs ourselves.

It's been on my todo list for a while, but unfortunately, I haven't had a chance to get to it.

**Comment by benubois** [comment]
I've started hitting this very frequently now. Is there anything that can be done in the interim besides not using nokogumbo? Maybe scanning the string ahead of time for the invalid characters?

**Comment by stevecheckoway** [comment]
You could replace U+0000 with U+FFFD. You can search the [HTML spec](https://html.spec.whatwg.org/) for `U+0000 NULL` to see what the parser is supposed to do when it encounters a 0 byte.

What are you doing that you're getting zero bytes? They're basically never valid in HTML.

**Comment by mesge** [comment]
@stevecheckoway Outlook regularly generates HTML emails containing null bytes. In email parsing this happens a lot. Typically we replace or remove U+0000.

**Comment by craigbarnes** [comment]
> This looks like a bug in the gumbo parser. This comment suggests the authors didn't consider embedded 0 bytes

The spec has rules for what to do with NUL bytes, depending on the tokenizer state. I'm pretty sure Gumbo implements it all, although it could have bugs.

FWIW, the example strings above all pass though lua-gumbo and produce the expected DOM (in this case the NUL bytes are dropped from the input stream).

**Comment by stevecheckoway** [comment]
The bug is in the handling of errors it seems. I'm writing tests now to confirm.
