### ISSUE TITLE
Markup errors not reported

### ISSUE THREAD

**Issue by gkellogg** [rubys/nokogumbo#67]
Prior to 1.5 (e.g., 1.4.13), Nokogumbo would report markup errors such as the following:

```sh
doc = Nokogiri::HTML5.parse('<!DOCTYPE html> <html')
doc.errors #==> [#<Nokogiri::XML::SyntaxError: 1:22: ERROR: @1:22: Tokenizer error with an unimplemented error message.
<!DOCTYPE html> <html
                     ^>] 
```

With 1.5, this error is no longer reported. Most likely due to a change in Gumbo, but unfortunate.

**Comment by rubys** [comment]
Try:

```
doc = Nokogiri::HTML5.parse('<!DOCTYPE html> <html', max_parse_errors: 100)
```

See: https://github.com/rubys/nokogumbo/pull/65

**Comment by gkellogg** [comment]
Thanks, that did it.
