### ISSUE TITLE
Error and blank output when calling `.to_html` on a parsed document containing a certain meta tag

### ISSUE THREAD

**Issue by steobrien** [rubys/nokogumbo#68]
Nokogiri version: 1.8.2
Nokogumbo version: 1.5.0

### Problem
Calling `to_html` on a parsed document containing a certain meta tag results in:
- a printed (but not raised) error
- an empty string erroneously being returned

### Quick reproduction
```ruby
input = <<~HTML
  <html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8; width=device-width">
    </head>
    <body>
      Hello!
    </body>
  </html>
HTML

Nokogiri::HTML5(input).to_html
# output error : unknown encoding utf-8; width=device-width
# => ""

```

**Comment by stevecheckoway** [comment]
This was fixed by https://github.com/rubys/nokogumbo/pull/57. I added a test for this in https://github.com/rubys/nokogumbo/pull/76 so that it doesn't regress.

Thanks for the bug report!
