### ISSUE TITLE
install failed on gentoo

### ISSUE THREAD

**Issue by Vonfry** [rubys/nokogumbo#69]
ruby version: `ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]`

gumbo version(portage): `0.10.1`

I can install nokogumbo with `portage`, but cannot install it with `gem` or `bundle`.

I try to read the [`ebuild`](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-ruby/nokogumbo/nokogumbo-1.5.0.ebuild) file  to config bundle, but I have no idea how to configure.

I also try to add `--with-ldflags=-Wl,--no-undefined`, it fails  as well.

```
$ gem install nokogumbo
Building native extensions. This could take a while...
ERROR:  Error installing nokogumbo:
        ERROR: Failed to build gem native extension.

    current directory: /home/git/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0/ext/nokogumboc
/usr/bin/ruby24 -r ./siteconf20180628-12916-1nvqzxo.rb extconf.rb
checking for xmlNewDoc() in -lxml2... yes
checking for nokogiri.h in /usr/lib64/ruby/gems/2.4.0/gems/nokogiri-1.8.1/ext/nokogiri... yes
checking for nokogiri.h in /usr/lib64/ruby/gems/2.4.0/gems/nokogiri-1.8.1/ext/nokogiri... yes
checking for gumbo_parse() in -lgumbo... yes
checking for GumboErrorType with error.h... not found
checking for GumboInsertionMode with insertion_mode.h... not found
checking for GumboParser with parser.h... not found
checking for GumboStringBuffer with string_buffer.h... not found
checking for GumboTokenType with token_type.h... not found
creating Makefile

current directory: /home/git/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0/ext/nokogumboc
make "DESTDIR=" clean

current directory: /home/git/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0/ext/nokogumboc
make "DESTDIR="
compiling nokogumbo.c
nokogumbo.c:24:10: fatal error: parser.h: No such file or directory
 #include "parser.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:242: nokogumbo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/git/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0 for inspection.
Results logged to /home/git/.gem/ruby/2.4.0/extensions/x86_64-linux/2.4.0/nokogumbo-1.5.0/gem_make.out
```

**Comment by Vonfry** [comment]
I find the reason.

After install dev-libs/gumbo on gentoo, lib isn't added in system lib dir.

I need to call `libtool --finish /usr/lib64`, which is a warning message when building.

**Comment by Vonfry** [comment]
Sorry, I haven't fix it. reopen

**Comment by Vonfry** [comment]
I find (these code](https://github.com/rubys/nokogumbo/blob/7b8946112a23ec6708938a5e7b33b0efb1733c1e/ext/nokogumboc/extconf.rb#L52-L58) are not run.

[this line](https://github.com/rubys/nokogumbo/blob/7b8946112a23ec6708938a5e7b33b0efb1733c1e/ext/nokogumboc/extconf.rb#L53)(`find_type`) has been called, you can find `xxx.h not found` at above.

But ! 

The [copy code] (https://github.com/rubys/nokogumbo/blob/7b8946112a23ec6708938a5e7b33b0efb1733c1e/ext/nokogumboc/extconf.rb#L56:24) is not run!! There is no file under the target directory.

**Comment by protegh** [comment]
As the [ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-ruby/nokogumbo/nokogumbo-1.5.0.ebuild) **removes** `-Wl,--no-undefined` from the ldflags:
```
sed -i -e 's:-Wl,--no-undefined::' ext/nokogumboc/Makefile || die
```
you should remove this too.

I had this problem with the [gitlabhq](https://gitlab.awesome-it.de/overlays/gitlab) ebuild (issue [64](https://gitlab.awesome-it.de/overlays/gitlab/issues/64)) and searched for the current ldflags of the failed nokogumbo install:
```
$ grep no-undefined /var/tmp/portage/www-apps/gitlabhq-10.8.5/image/opt/gitlabhq-10.8/vendor/bundle/ruby/2.3.0/gems/nokogumbo-1.5.0/ext/nokogumboc/Makefile
ldflags  = -L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--no-undefined
```
removed `-Wl,--no-undefined` from them and added this line to the `gitlabhq-10.8.5.ebuild`:
```
    ${BUNDLE} config build.nokogumbo --with-ldflags='-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic'
```
and the bundle install finished without error.

**Comment by Vonfry** [comment]
@protegh thanks, I try to run `gem install nokogumbo -- --with-ldflags='-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic'`, and then success!
Now, I use it for bundle.

**Comment by limansky** [comment]
Hi,

`gem install nokogumbo -- --with-ldflags='-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic'` doesn't work for me on Gentoo with Ruby 2.4.4.

```
$ gem install nokogumbo -- --with-ldflags='-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic'
Fetching: nokogumbo-1.5.0.gem (100%)
Building native extensions with: '--with-ldflags=-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic'
This could take a while...
ERROR:  Error installing nokogumbo:
	ERROR: Failed to build gem native extension.

    current directory: /mnt/data/gitlab/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0/ext/nokogumboc
/usr/bin/ruby24 -r ./siteconf20180630-4278-tdp4z5.rb extconf.rb --with-ldflags=-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic
checking for xmlNewDoc() in -lxml2... yes
checking for nokogiri.h in /mnt/data/gitlab/.gem/ruby/2.4.0/gems/nokogiri-1.8.3/ext/nokogiri... yes
checking for nokogiri.h in /mnt/data/gitlab/.gem/ruby/2.4.0/gems/nokogiri-1.8.3/ext/nokogiri... yes
checking for gumbo_parse() in -lgumbo... yes
checking for GumboErrorType with error.h... not found
checking for GumboInsertionMode with insertion_mode.h... not found
checking for GumboParser with parser.h... not found
checking for GumboStringBuffer with string_buffer.h... not found
checking for GumboTokenType with token_type.h... not found
creating Makefile

current directory: /mnt/data/gitlab/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0/ext/nokogumboc
make "DESTDIR=" clean

current directory: /mnt/data/gitlab/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0/ext/nokogumboc
make "DESTDIR="
compiling nokogumbo.c
nokogumbo.c:24:20: fatal error: parser.h: No such file or directory
 #include "parser.h"
                    ^
compilation terminated.
make: *** [Makefile:242: nokogumbo.o] Error 1

make failed, exit code 2

Gem files will remain installed in /mnt/data/gitlab/.gem/ruby/2.4.0/gems/nokogumbo-1.5.0 for inspection.
Results logged to /mnt/data/gitlab/.gem/ruby/2.4.0/extensions/x86-linux/2.4.0/nokogumbo-1.5.0/gem_make.out
```

**Comment by limansky** [comment]
It made a trick for me after I removed nokogiri & gumbo installed via portage

**Comment by kaspergrubbe** [comment]
@limansky THANKS!

This did the trick:

```
gem install nokogumbo -v '1.4.13' -- --with-ldflags='-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic'
```

And also:

```
bundle config build.nokogumbo --with-ldflags="-L. -Wl,-O1 -Wl,--as-needed -fstack-protector -rdynamic -Wl,-export-dynamic"
```

**Comment by stevecheckoway** [comment]
@kaspergrubbe Does 2.0.0 not work for you?

**Comment by kaspergrubbe** [comment]
@stevecheckoway I would love to test it out, but we rely on the `sanitize`-gem (newest version) which is versionlocked to `nokogumbo (~> 1.4)`.

**Comment by stevecheckoway** [comment]
@kaspergrubbe Gotcha. I took a look at the `sanitize` gem and updating to 2.0.0 does actually require some work. The tests bake in some of the old behavior that changed (such as adding trailing newlines) and libxml's serialization of html (including some work arounds that aren't needed). Libxml2's behavior is incorrect in some cases and simply different from the standard in others.

Differences include
1. newlines that libxml2 inserted that Nokogumbo no longer does
2. libxml2 encoded `<` and `>` as `&lt;` and `&gt;` in attribute values but the spec doesn't say to do so Nokogumbo no longer does;
3. libxml2 doesn't always encode `"` as `&quot;` in attribute values but the spec says to do so, so Nokogumbo does
4. libxml2 preserves public and system identifiers in DOCTYPEs. The spec drops them when serializing so Nokogumbo does as well.

I'll make a PR and see if they have any interest in updating.

**Comment by rubys** [comment]
cc: @rgrove ; upgrading to 2.0 is highly recommended

**Comment by rgrove** [comment]
Hi! I hadn't noticed the 2.0.0 release yet, but I'm definitely interested in using it in Sanitize. I'm a bit swamped at the moment, but a PR would be very welcome.

**Comment by stevecheckoway** [comment]
@rgrove https://github.com/rgrove/sanitize/pull/189
