### ISSUE TITLE
Incorporate gumbo fixes from lua-gumbo

### ISSUE THREAD

**Issue by stevecheckoway** [rubys/nokogumbo#81]
lua-gumbo has made a [bunch of improvements](https://github.com/craigbarnes/lua-gumbo/tree/master/lib#libgumbo) to gumbo. We should incorporate their fixes!

- [x] https://github.com/craigbarnes/lua-gumbo/commit/91cef89: Re-implement `adjust_foreign_attributes()` with a gperf hash
- [x] https://github.com/craigbarnes/lua-gumbo/commit/b11abe7: Pass `TagSet` arrays into functions by reference instead of value
- [x] https://github.com/craigbarnes/lua-gumbo/commit/b73dc03: Simplify `maybe_replace_codepoint()` function
- [x] https://github.com/craigbarnes/lua-gumbo/commit/d5d0bb3: Remove special handling of `<menuitem>` tag
- [x] https://github.com/craigbarnes/lua-gumbo/commit/7bd5162: Remove special handling of `<isindex>` tag
- [x] https://github.com/craigbarnes/lua-gumbo/commit/a5c1b0e: Use `realloc(3)` instead of `malloc(3)` in `enlarge_vector_if_full()`
- [x] https://github.com/craigbarnes/lua-gumbo/commit/dcbebd7: Use `realloc(3)` instead of `malloc(3)` in `maybe_resize_string_buffer()`
- [x] https://github.com/craigbarnes/lua-gumbo/commit/df15262: Make `destroy_node()` function non-recursive
- [x] https://github.com/craigbarnes/lua-gumbo/commit/2df37f5: Fix signedness of some format specifiers
- [x] https://github.com/craigbarnes/lua-gumbo/commit/176553e: Add maximum element nesting limit
- [x] https://github.com/craigbarnes/lua-gumbo/commit/bed0f4a: Annotate `gumbo_debug()` with `PRINTF` macro and fix warnings
- [x] https://github.com/craigbarnes/lua-gumbo/commit/7ffc218: Annotate `print_message()` with `PRINTF` macro and fix warnings
- [x] https://github.com/craigbarnes/lua-gumbo/commit/1bd8ab5, https://github.com/craigbarnes/lua-gumbo/commit/9136507, https://github.com/craigbarnes/lua-gumbo/commit/53a1f9a: Deduplicate some identical `TagSet` arrays
- [x] https://github.com/craigbarnes/lua-gumbo/commit/a7a9065: Add some GCC/Clang function attributes
- [x] https://github.com/craigbarnes/lua-gumbo/commit/8d3d4e4: Remove custom allocator support
- [x] https://github.com/craigbarnes/lua-gumbo/commit/8d3b006: Fix recording of source positions for `</form>` end tags
- [x] https://github.com/craigbarnes/lua-gumbo/commit/1a8d763: Replace linear search in `maybe_replace_codepoint()` with a lookup table
- [x] https://github.com/craigbarnes/lua-gumbo/commit/6dca79e: Replace `strcasecmp()` and `strncasecmp()` with ascii-only equivalents
- [x] https://github.com/craigbarnes/lua-gumbo/commit/17ab1d2: Fix `TAGSET_INCLUDES` macro to work properly with multiple bit flags
- [x] https://github.com/craigbarnes/lua-gumbo/commit/7e56d45: Re-implement `gumbo_normalize_svg_tagname()` with a gperf hash
- [x] https://github.com/craigbarnes/lua-gumbo/commit/a518d35: Replace linear array search in `adjust_svg_attributes()` with a gperf hash
- [x] https://github.com/craigbarnes/lua-gumbo/commit/a4a7433: Fix duplicate `TagSet` initializer being ignored in `is_special_node()`
- [x] https://github.com/craigbarnes/lua-gumbo/commit/8137fcd: Add support for `<dialog>` tag
- [x] https://github.com/craigbarnes/lua-gumbo/commit/4b35471: Add missing `static` qualifiers to hide symbols that shouldn't be extern
- [x] https://github.com/craigbarnes/lua-gumbo/commit/df57c59, https://github.com/craigbarnes/lua-gumbo/commit/03101f3, https://github.com/craigbarnes/lua-gumbo/commit/ea62330: Replace use of locale-dependant `ctype.h` functions with custom, ASCII-only equivalents

**Comment by craigbarnes** [comment]
Note: the following pairs are probably best merged into single commits:

* craigbarnes/lua-gumbo@1a8d763 and craigbarnes/lua-gumbo@b73dc03
* craigbarnes/lua-gumbo@a4a7433 and craigbarnes/lua-gumbo@17ab1d2

These should be easy to cherry-pick without requiring any earlier commits:

* craigbarnes/lua-gumbo@df15262
* craigbarnes/lua-gumbo@7bd5162
* craigbarnes/lua-gumbo@d5d0bb3
* craigbarnes/lua-gumbo@8137fcd

The rest probably need to be done bottom to top. I threw out the original Python generator scripts and autotools build system, so a few commits might also need adjusting to account for that too.

**Comment by rubys** [comment]
Any chance of a shared common codebase?

**Comment by craigbarnes** [comment]
To be honest, probably not. After seeing some of the conflicting feature requests and ABI stability woes the original author had to deal with, I'm kind of glad to be using a fork.

FWIW, there's really not that much substance in the above commits. The larger ones are purely for performance. The rest are mostly trivial. IMO the library was in pretty good shape by the time it was abandoned. The only part noticeably buggier than the rest seems to be `error.c`, but I'm not using that in lua-gumbo.

**Comment by stevecheckoway** [comment]
@craigbarnes If you ever decide to use the error portion, I had a few fixes
- https://github.com/rubys/nokogumbo/commit/c685435dbce85dd68412b51b580f9758a96d4009 Handle zero bytes in the input without crashing and add missing parse error.
- https://github.com/rubys/nokogumbo/commit/60fa74799329d6cd3f2770fcabf3ccf22ca8d94c Improve the error API _slightly_ by adding explicit lengths.

The error API could be improved further (and more error messages could be implemented), but it's pretty low priority.

**Comment by craigbarnes** [comment]
> Let me ask the question a different way. Are you willing to accept patches to the gumbo parser even if the fixes are to portions of the code that you aren't currently using (e.g., the error API)?

Yes. I intend to eventually clean up and use the error API anyway. I don't foresee removing anything from the library, besides the already removed custom allocator support.

> Previously, nokogumbo got access to the source code of gumbo-parser as a git submodule. Is there any reason that nokogumbo couldn't have lua-gumbo as a git submodule

There's no reason you couldn't. I'm fine with people using the fork via whatever method they prefer, so long as they're ok with having no guarantees of API stability.

> Downside to lua-gumo: some of those fixes may be to code that you don't use, or conceivably could even break lua-gumbo.

The former is fine by me. I won't merge anything that will break the Lua bindings though.

> 1. we create a joint fork of gumbo-parser and shed the parts we don't need and both projects import that codebase.

That would just invite the question "why not a shared library"? The only thing I'm adamantly against is maintaining a shared library (even jointly).

> 2. we put lua-gumbo and nokogumbo into a common repository and the build and test process produces and verifies two outputs.

It seems like that would just clutter the git history of both projects. Depending on what happens down the line, I may change my mind, but for now the option that sounds most agreeable to me is nokogumbo using lua-gumbo as a submodule.

**Comment by craigbarnes** [comment]
> If you ever decide to use the error portion, I had a few fixes
>
> `c685435` Handle zero bytes in the input without crashing and add missing parse error.

@stevecheckoway Is this specifically triggered by calling `gumbo_caret_diagnostic_to_string()`? I'll pull your fix when I get some time to write a few test cases.

> The error API could be improved further (and more error messages could be implemented), but it's pretty low priority.

Yeah, it needs a complete overhaul really. In the original libgumbo, it wasn't installed by "make install" and was considered a private/internal header. How much of the API is exposed in nokogumbo?

**Comment by craigbarnes** [comment]
> `GUMBO_STATUS_OUT_OF_MEMORY` seems unused. 

It is unused at the moment. I envisioned improving OOM handling in the future by using a status code instead of calling `abort()`, but that hasn't been implemented yet.

> What's the rationale behind a 400-deep limit for GUMBO_STATUS_TREE_TOO_DEEP?

* Preventing google/gumbo-parser#393.
* Preventing a recursive tree builder overflowing the stack. 
* Preventing possible DoS attack by `"<div>".repeat(2^50)`

The limit was originally 512, to match the one used by WebKit. I reduced it to 400 to work around what seems to be a bug in OpenBSD causing excessive stack usage.

> 1. writing some code to pull patches from lua-gumbo, change paths (from lib/blah to gumbo-parser/src/blah) and omit patches to files outside the lib;
> 2. reseting nokogumbo's copy of gumbo-parser to the same version you started with;
> 3. applying all of the patches in order; and
> 4. re-implementing my patches on top of yours ace07d0.

It seems to have worked pretty well anyway. It took me a lot longer than that to create the original commits.

> It might be easier for you to grab ace07d0 than my previous commits.

Thanks. I'll take a look at that in a while.

**Comment by stevecheckoway** [comment]
This all sounds good to me.

What do you do when the limit is hit? Do you return a partial tree in lua? @rubys, do you have any thoughts about what nokogumbo should do in this case?

**Comment by craigbarnes** [comment]
> What do you do when the limit is hit? Do you return a partial tree in lua?

I just call `gumbo_destroy_output()` and return an error. I considered returning a partial tree with a boolean field marking it as such, but the possibility of people just ignoring it and treating it like a complete tree seemed too likely. If I were going to make it possible to get the partial tree, I'd probably add some kind of option to explicitly request it beforehand. We're probably talking about a fraction of 1% edge case here though.

**Comment by stevecheckoway** [comment]
That seems sensible to me.

**Comment by craigbarnes** [comment]
> It might be easier for you to grab ace07d0 than my previous commits.

I couldn't figure out why your test cases wouldn't crash lua-gumbo, even without your patch applied.

It seems I added a [commit](https://github.com/craigbarnes/lua-gumbo/commit/9cfa7f8295c2e5059ec9df99b36ebea5947098dc) a while back that might have fixed the same issue. I'm not sure if it fully fixes the same issue you were having or how much my patch overlaps with yours.

**Comment by craigbarnes** [comment]
Ah, I remember why I made that commit now. It was to prevent `error->position.column - 1` wrapping around to `SIZE_MAX` if `error->position.column` is zero. So it's not related to your ace07d0 commit.

> ... are you perhaps compiling with `NDEBUG`

No. I haven't been using `NDEBUG` even for release builds.

**Comment by craigbarnes** [comment]
> I haven't used gtest before, but it looks reasonably simple.

I just spent some time converting most of the C++ unit tests to C, although they still mostly look like gtest fixtures. I want to throw out the gtest/C++ dependency altogether when the rest are converted.

**Comment by stevecheckoway** [comment]
@craigbarnes Why not incorporate `SETUP()` and `TEARDOWN()` into `TEST_F` rather than writing them on every test that needs them. Those that don't just define them to empty.

Something like this (untested)
``` c
#define TEST_F(group, name) \
static inline void group ## name ## _inner(void); \
static void CONSTRUCTOR group ## name(void) { \
  SETUP(); \
  group ## name ## _inner(); \
  TEARDOWN(); \
} \
void group ## name ## _inner(void)
```

I think this will also work with failing assertions which return without calling `TEARDOWN()` right now.

The `ASSERT_` macros also have issues with side-effects. I think the canonical way to deal with this is to have each macro expand to a call to a function that passes `__FILE__`, `__LINE__`, and the assertion to deal with that.

Here's some code that will allegedly work with visual studio for constructors. https://stackoverflow.com/a/2390626

**Comment by craigbarnes** [comment]
> Why not incorporate `SETUP()` and `TEARDOWN()` into `TEST_F` rather than writing them on every test that needs them

I thought about that, but I wanted to just convert everything first before getting too complex with the macros. I like your idea though, but it doesn't seem to work as-is. If it's possible to do something like that without too much extra contortion I'm all for it.

> The ASSERT_ macros also have issues with side-effects. I think the canonical way to deal with this is to have each macro expand to a call to a function that passes __FILE__, __LINE__, and the assertion to deal with that.

I'm working on this at the moment.

> Here's some code that will allegedly work with visual studio for constructors

I came across that thread too. I didn't attempt to incorporate it because I don't have any Windows machines to test with, except for the Appveyor CI setup.

**Comment by stevecheckoway** [comment]
Addressed by https://github.com/rubys/nokogumbo/pull/84!
